### PR TITLE
support nrf52811

### PR DESCRIPTION
**Pull request by placrosse**

### CODE REVIEW

**Comment by jonas-schievink** [comment]
Thanks for the PR! If you could rebase this onto current master, that should let CI pass – I've unified the `skipaddr` configuration so that it should work for all chips now.

**Comment by placrosse** [comment]
Good to go?

**Comment by placrosse** [comment]
Possible to make a 0.1.0 release to crates.io?

**Comment by placrosse** [comment]
Should be updated now.

Any plans to release a 0.1.0 to crates.io?

**Comment by jonas-schievink** [comment]
Hmm, looks like you rebased commits from master onto this branch. Please rebase only 8e02f152c59df924daa3afcfaba2a425064b9879 onto master.

**Pull request closed without merging**
