### PR TITLE
Disable default-features for HALs

### LINKED ISSUE #88: -hal crate configuration conflict
Hi!

I'm trying to use rubble in combination with the dwm1001 crate, but it looks like in order to do so, the `nrf52832-hal` crate, a mutual dependency, needs to be configured with the same features across the board or the project fails to compile. 

```
error: failed to run custom build command for `nrf52832-hal v0.8.1`                                                 
                                                                                                                    
Caused by:                                                                                                          
  process didn't exit successfully: `/home/owen/projects/embedded-trainings/beginner-lite/templates/segment-1/target
/debug/build/nrf52832-hal-7553567355a8bf89/build-script-build` (exit code: 101)                                     
--- stderr                                                                                                          
thread 'main' panicked at '                                                                                         
                                                                                                                    
Must select exactly one package for linker script generation!                                                       
Choices: 'xxAA-package' or 'xxAB-package'                                                                           

', /home/owen/.cargo/registry/src/github.com-1ecc6299db9ec823/nrf52832-hal-0.8.1/build.rs:12:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

I noticed that rubble uses the default features:

- https://github.com/jonas-schievink/rubble/blob/master/rubble-nrf52/Cargo.toml#L15

whereas the dwm1001 crate elects to specify something else:

- https://github.com/braun-embedded/rust-dw1000/blob/master/dwm1001/Cargo.toml#L42

I was able to clone rubble and modify the manifest to align the feature selection and my project compiles, but this is as far as I've gone to troubleshoot.

Seems like it may be possible to expose features in `rubble-nrf52` to allow dependents to control this, but I'm not sure of the impact of doing this.

That's all I know - looking for input on how to proceed.
Thanks for your work on this!

### PR DESCRIPTION
**Pull request by dbrgn**
Otherwise we'll get conflicting memory configs.

Closes #88

### CODE REVIEW

**Comment by jonas-schievink** [comment]
Hmm, this will mean that users cannot depend on `rubble-nrf5x` without also depending on the HAL. I wonder if that's okay?

**Comment by dbrgn** [comment]
Well, the current state is not being able to use `rubble-nrf5x` at all, unless depending on the same (default) device variant :wink: 

What we could also do is passing through the features:

```toml
[features]
xxAA-package = ["nrf52832-hal/xxAA-package"]
xxBB-package = ["nrf52832-hal/xxBB-package"]
```

...however, that gets messy quickly (especially if the HAL adds more flags). I think the probability of an application that depends on `rubble-nrf5x` but not also on the HAL is very low.

**Comment by jonas-schievink** [comment]
Yeah, I think it's a clear improvement.

**Comment by dbrgn** [comment]
Thanks!

**Pull request merged**
