### PR TITLE
Fix `rubble-demo` gdbinit

### PR DESCRIPTION
**Pull request by chocol4te**
Moving the `.cargo` directory from the root to the `rubble-demo` crate breaks using `cargo run` from the root.

This PR adds documentation showing how the demo can be run and moves the example `.gdbinit`.

I'm not super happy about the addition to the README, I'm not sure how clear it is, or if it belongs there.

### CODE REVIEW

**Comment by jonas-schievink** [comment]
Looks like `build.rs` can also be deleted now

**Comment by chocol4te** [comment]
We couldn't move it to rubble-demo too?

**Comment by jonas-schievink** [comment]
Well you already added what it would do to the instructions. I'd say just remove it, it isn't that helpful of a script.

**Comment by chocol4te** [comment]
Done :)

**Pull request merged**
