### PR TITLE
Nrf52 Radio: Adds compiler fences to DMA code

### PR DESCRIPTION
**Pull request by thalesfragoso**

### CODE REVIEW

**Comment by thalesfragoso** [comment]
Formatting...

**Comment by jonas-schievink** [comment]
Thanks! This looks good to me, even though I'm not too familiar with how these fences work exactly. Using Acquire/Release semantics instead of the more conservative SeqCst the nrf52-hal uses also seems correct to me.

**Comment by thalesfragoso** [comment]
> Thanks! This looks good to me, even though I'm not too familiar with how these fences work exactly. Using Acquire/Release semantics instead of the more conservative SeqCst the nrf52-hal uses also seems correct to me.

Not sure if you already looked at this but I can recommend it for a quick read:
https://docs.rust-embedded.org/embedonomicon/dma.html

**Comment by jonas-schievink** [comment]
Ah yeah that explains it, thanks! It's been a while since I've read that book...

**Pull request merged**
