### PR TITLE
Add a P-256 crypto provider API

### PR DESCRIPTION
**Pull request by jonas-schievink**
2 providers are built in: ring and nisty. (cc @nickray if you're interested in this)

This should unblock pairing support.

**DO NOT MERGE** until nisty is published on crates.io (this uses ECDH, which is only in master).

Closes https://github.com/jonas-schievink/rubble/issues/40

### CODE REVIEW

**Comment by nickray** [comment]
Neat! I was thinking of waiting for some feedback, and maybe adding key agreement and point compression before the release. But if you have need, I'll publish earlier.

**Comment by nickray** [comment]
I published `0.1.0-alpha.1` which contains key agreement (also serialization to ASN.1 DER as optional feature).

**Comment by jonas-schievink** [comment]
Hmm, I can't get it to build with the updated version, since `log` pulls in libstd now. Probably because of the bindgen dependency?

**Comment by nickray** [comment]
Ughh... I managed to build your `nrf52-demo` for 52840 by disabling the bindgen default-features, published as nisty 0.1.0-alpha.2 and micro-ecc-sys 0.3.1. Any build issues left, or other test cases you have?
Of course this is a bit whack-a-mole, but I'd currently prefer keeping bindgen for ease of use. Thoughts on this?

**Comment by jonas-schievink** [comment]
Thanks a lot, looks like that works!

**Comment by jonas-schievink** [comment]
wtf this is llvm 3.8

**Comment by jonas-schievink** [comment]
Hmm, not sure why micro-ecc-sys is trying to include `/usr/include/x86_64-linux-gnu/gnu/stubs.h` during binding generation. That seems wrong.

**Comment by jonas-schievink** [comment]
This uses `p256` instead of `nisty` now, which solves all the FFI problems

**Pull request merged**
